import { IScannerRule } from '../types/scanner';
import { Severity, FindingCategory } from '../types/finding';

export const credentialRules: IScannerRule[] = [
  {
    id: 'CRED-001',
    title: 'AWS Access Key Detected',
    description: 'An AWS Access Key ID (long-term AKIA or temporary session ASIA) was found in the code. Move this to environment variables or a secrets manager.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-002',
    title: 'AWS Secret Key Detected',
    description: 'A potential AWS Secret Access Key was found. Never commit secrets to source control.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /(?:aws_secret_access_key|aws_secret|secret_key)\s*[:=]\s*['"]?[A-Za-z0-9/+=]{40}['"]?/gi,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-003',
    title: 'Generic API Key Detected',
    description: 'A hardcoded API key was found. Use environment variables or a secrets manager instead.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    // Quotes optional (so .env/shell/YAML match); charset includes - and _.
    pattern: /(?:api[_-]?key|apikey)["']?\s*[:=]\s*['"]?([A-Za-z0-9_\-]{20,})['"]?/gi,
    secretGroup: 1,
    minEntropy: 3.0,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-004',
    title: 'Private Key Detected',
    description: 'A private key was found in the source code. Private keys should never be stored in code.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /-----BEGIN\s+(?:RSA|DSA|EC|OPENSSH|PGP)?\s*PRIVATE KEY-----/g,
    cweId: 'CWE-321',
  },
  {
    id: 'CRED-005',
    title: 'Hardcoded Password Detected',
    description: 'A hardcoded password was found. Use environment variables or a secrets manager.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    // Matches DB_PASSWORD=, userPassword:, etc. Quotes optional; placeholder and
    // low-entropy values are filtered by the engine heuristics.
    pattern: /(?:password|passwd|pwd)["']?\s*[:=]\s*['"]?([^\s'"]{4,})['"]?/gi,
    secretGroup: 1,
    minEntropy: 2.5,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-006',
    title: 'GitHub Token Detected',
    description: 'A GitHub personal access token was found. Rotate this token immediately and use environment variables.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /ghp_[A-Za-z0-9_]{36}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-007',
    title: 'GitHub OAuth Token Detected',
    description: 'A GitHub OAuth access token was found in the code.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /gho_[A-Za-z0-9_]{36}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-008',
    title: 'Slack Token Detected',
    description: 'A Slack token was found in the code. Rotate and store securely.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /xox[baprs]-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-009',
    title: 'Generic Secret Assignment',
    description: 'A potential secret was found hardcoded in the source. Move to environment variables.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    // Quotes optional; covers secret/token/auth and the common *_secret/*_token forms.
    pattern: /(?:client[_-]?secret|api[_-]?secret|access[_-]?token|refresh[_-]?token|secret|token|auth)["']?\s*[:=]\s*['"]?([A-Za-z0-9_\-+/=.]{16,})['"]?/gi,
    secretGroup: 1,
    minEntropy: 3.0,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-010',
    title: 'Connection String with Credentials',
    description: 'A database connection string with embedded credentials was detected.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /(?:mongodb(?:\+srv)?|postgres(?:ql)?|mysql|mariadb|rediss?|amqps?|mssql|sqlserver|https?):\/\/[^:\s/@]+:[^@\s/]+@[^/\s]+/gi,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-011',
    title: 'Google API Key Detected',
    description: 'A Google API key was found. Restrict key usage and use environment variables.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /AIza[0-9A-Za-z_-]{35}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-012',
    title: 'Stripe Secret Key Detected',
    description: 'A Stripe secret key was found. This grants full API access. Rotate immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /sk_live_[0-9a-zA-Z]{24,}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-013',
    title: 'JWT Token Detected',
    description: 'A hardcoded JWT token was found. Tokens should be generated dynamically.',
    severity: Severity.Medium,
    category: FindingCategory.Credential,
    pattern: /eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-014',
    title: 'GitHub Token Detected (server/user/refresh)',
    description: 'A GitHub server (ghs_), user-to-server (ghu_) or refresh (ghr_) token was found. Rotate immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bgh[sur]_[A-Za-z0-9]{36}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-015',
    title: 'GitHub Fine-Grained PAT Detected',
    description: 'A GitHub fine-grained personal access token was found. Rotate immediately and use a secrets manager.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bgithub_pat_[0-9a-zA-Z_]{82}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-016',
    title: 'GitLab Personal Access Token Detected',
    description: 'A GitLab personal access token (glpat-) was found. Rotate immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bglpat-[0-9a-zA-Z_-]{20}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-017',
    title: 'npm Access Token Detected',
    description: 'An npm access token (npm_) was found. Rotate it and use an .npmrc with an environment variable.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bnpm_[0-9a-zA-Z]{36}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-018',
    title: 'PyPI API Token Detected',
    description: 'A PyPI upload token (pypi-) was found. Rotate it on PyPI immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{50,}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-019',
    title: 'Hugging Face Token Detected',
    description: 'A Hugging Face access token (hf_) was found. Rotate it in your account settings.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /\bhf_[A-Za-z0-9]{34}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-020',
    title: 'OpenAI API Key Detected',
    description: 'An OpenAI API key was found. Rotate it immediately; it grants billable API access.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bsk-(?:proj-[A-Za-z0-9_-]{40,}|[A-Za-z0-9]{20}T3BlbkFJ[A-Za-z0-9]{20,})\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-021',
    title: 'Anthropic API Key Detected',
    description: 'An Anthropic API key (sk-ant-) was found. Rotate it immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bsk-ant-[A-Za-z0-9-]{2,}-[A-Za-z0-9_-]{80,}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-022',
    title: 'Google OAuth Client Secret Detected',
    description: 'A Google OAuth client secret (GOCSPX-) was found. Rotate it in the Google Cloud console.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /\bGOCSPX-[A-Za-z0-9_-]{28}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-023',
    title: 'Slack Incoming Webhook Detected',
    description: 'A Slack incoming webhook URL was found. Anyone with this URL can post to the channel; rotate it.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /https:\/\/hooks\.slack\.com\/services\/T[A-Za-z0-9_]+\/B[A-Za-z0-9_]+\/[A-Za-z0-9_]{20,}/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-024',
    title: 'Stripe Restricted Key Detected',
    description: 'A Stripe restricted API key (rk_live_) was found. Rotate it immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\brk_live_[0-9a-zA-Z]{24,}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-025',
    title: 'Stripe Webhook Secret Detected',
    description: 'A Stripe webhook signing secret (whsec_) was found. Rotate it in the Stripe dashboard.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /\bwhsec_[A-Za-z0-9]{32,}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-026',
    title: 'SendGrid API Key Detected',
    description: 'A SendGrid API key (SG.) was found. Rotate it immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-027',
    title: 'Twilio API Key Detected',
    description: 'A Twilio API key SID (SK...) was found. Rotate it in the Twilio console.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /\bSK[0-9a-fA-F]{32}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-028',
    title: 'Sentry DSN Detected',
    description: 'A Sentry DSN was found. Treat it as a secret if it includes a private key component.',
    severity: Severity.Medium,
    category: FindingCategory.Credential,
    pattern: /https:\/\/[0-9a-f]{32}@(?:[a-z0-9.-]+\.)?(?:ingest\.)?sentry\.io\/[0-9]+/gi,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-029',
    title: 'DigitalOcean Token Detected',
    description: 'A DigitalOcean personal access / OAuth token (do?_v1_) was found. Rotate it immediately.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /\bdo[oprv]_v1_[a-f0-9]{64}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-030',
    title: 'Discord Bot Token Detected',
    description: 'A Discord bot token was found. Rotate it in the Discord developer portal.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /\b[MNO][A-Za-z0-9_-]{23}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-031',
    title: 'Telegram Bot Token Detected',
    description: 'A Telegram bot token was found. Rotate it via BotFather.',
    severity: Severity.High,
    category: FindingCategory.Credential,
    pattern: /\b\d{8,10}:[A-Za-z0-9_-]{35}\b/g,
    cweId: 'CWE-798',
  },
  {
    id: 'CRED-032',
    title: 'Azure Storage Account Key Detected',
    description: 'An Azure Storage account key was found in a connection string. Rotate the key in the Azure portal.',
    severity: Severity.Critical,
    category: FindingCategory.Credential,
    pattern: /AccountKey=[A-Za-z0-9+/]{86}==/gi,
    cweId: 'CWE-798',
  },
];
