import { IScannerRule } from '../types/scanner';
import { Severity, FindingCategory } from '../types/finding';

export const owaspRules: IScannerRule[] = [
  // A03:2021 - Injection
  {
    id: 'OWASP-001',
    title: 'Potential SQL Injection',
    description: 'String concatenation in SQL query detected. Use parameterized queries instead.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:query|execute|exec)\s*\(\s*['"`](?:SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER)\s[^'"`]*['"`]\s*\+/gi,
    languages: ['javascript', 'typescript', 'python', 'java', 'php'],
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-002',
    title: 'SQL Injection via Template Literal',
    description: 'SQL query uses template literal with interpolated values. Use parameterized queries.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:query|execute|exec)\s*\(\s*`(?:SELECT|INSERT|UPDATE|DELETE|DROP)\s[^`]*\$\{/gi,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-003',
    title: 'Use of eval() - Code Injection Risk',
    description: 'eval() executes arbitrary code and is a major security risk. Avoid eval entirely.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    // Exclude method calls like model.eval()/df.eval() (PyTorch/pandas) and
    // identifiers ending in eval (e.g. ast.literal_eval handled by the \w guard).
    pattern: /(?<![.\w])eval\s*\(/g,
    languages: ['javascript', 'typescript', 'python'],
    cweId: 'CWE-95',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-004',
    title: 'Use of Function() Constructor',
    description: 'The Function constructor creates functions from strings, similar to eval(). Avoid it.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /new\s+Function\s*\(/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-95',
    owaspId: 'A03:2021',
  },
  // A03:2021 - XSS
  {
    id: 'OWASP-005',
    title: 'Potential XSS via innerHTML',
    description: 'Setting innerHTML with dynamic content can lead to XSS. Use textContent or sanitize input.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /\.innerHTML\s*=/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-79',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-006',
    title: 'Potential XSS via document.write',
    description: 'document.write() can introduce XSS vulnerabilities. Use DOM manipulation methods instead.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /document\.write\s*\(/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-79',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-007',
    title: 'React dangerouslySetInnerHTML',
    description: 'dangerouslySetInnerHTML can lead to XSS if not properly sanitized.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /dangerouslySetInnerHTML/g,
    languages: ['javascript', 'typescript', 'javascriptreact', 'typescriptreact'],
    cweId: 'CWE-79',
    owaspId: 'A03:2021',
  },
  // A08:2021 - Insecure Deserialization
  {
    id: 'OWASP-008',
    title: 'Insecure Deserialization (pickle)',
    description: 'pickle.loads() can execute arbitrary code. Use json or safe alternatives.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /pickle\.loads?\s*\(/g,
    languages: ['python'],
    cweId: 'CWE-502',
    owaspId: 'A08:2021',
  },
  {
    id: 'OWASP-009',
    title: 'Insecure YAML Loading',
    description: 'yaml.load() without SafeLoader can execute arbitrary code. Use yaml.safe_load() instead.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /yaml\.load\s*\((?![^)]*SafeLoader)[^)]*\)/g,
    languages: ['python'],
    cweId: 'CWE-502',
    owaspId: 'A08:2021',
  },
  // A02:2021 - Cryptographic Failures
  {
    id: 'OWASP-010',
    title: 'Weak Cryptographic Algorithm (MD5)',
    description: 'MD5 is cryptographically broken. Use SHA-256 or stronger algorithms.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    // Two shapes: the algorithm is in the function name (hashlib.md5(...),
    // CryptoJS.MD5(...)) or in the argument (createHash('md5'),
    // MessageDigest.getInstance("MD5")).
    pattern: /(?:hashlib\.md5|CryptoJS\.MD5)\s*\(|(?:createHash|MessageDigest\.getInstance)\s*\(\s*['"]md5['"]/gi,
    cweId: 'CWE-327',
    owaspId: 'A02:2021',
  },
  {
    id: 'OWASP-011',
    title: 'Weak Cryptographic Algorithm (SHA1)',
    description: 'SHA-1 is deprecated for security use. Use SHA-256 or stronger.',
    severity: Severity.Medium,
    category: FindingCategory.OWASP,
    pattern: /(?:hashlib\.sha1|CryptoJS\.SHA1)\s*\(|(?:createHash|MessageDigest\.getInstance)\s*\(\s*['"]sha-?1['"]/gi,
    cweId: 'CWE-327',
    owaspId: 'A02:2021',
  },
  // A07:2021 - Command Injection
  {
    id: 'OWASP-012',
    title: 'Potential Command Injection',
    description: 'User input in shell commands can lead to command injection. Use parameterized commands.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:exec|spawn|execSync|spawnSync|system|popen)\s*\(\s*(?:['"`][^'"`]*['"`]\s*\+|`[^`]*\$\{)/g,
    cweId: 'CWE-78',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-013',
    title: 'Python os.system() Usage',
    description: 'os.system() is vulnerable to command injection. Use subprocess with shell=False.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /os\.system\s*\(/g,
    languages: ['python'],
    cweId: 'CWE-78',
    owaspId: 'A03:2021',
  },
  // A05:2021 - Security Misconfiguration
  {
    id: 'OWASP-014',
    title: 'Disabled CSRF Protection',
    description: 'CSRF protection appears to be disabled. Ensure CSRF tokens are validated.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:csrf|xsrf)\s*[:=]\s*(?:false|disabled|off)/gi,
    cweId: 'CWE-352',
    owaspId: 'A05:2021',
  },
  // A01:2021 - Broken Access Control
  {
    id: 'OWASP-015',
    title: 'Potential Path Traversal',
    description: 'File path constructed from user input may allow path traversal attacks.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:readFile|readFileSync|open|createReadStream)\s*\(\s*(?:req\.|request\.|params\.|query\.)/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-22',
    owaspId: 'A01:2021',
  },
  {
    id: 'OWASP-016',
    title: 'SQL Injection via f-string',
    description: 'A SQL statement is built with a Python f-string. Use parameterized queries (e.g. cursor.execute(sql, params)).',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:execute|executemany|query|raw)\s*\(\s*f['"](?:SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER)\b[^'"]*\{/gi,
    languages: ['python'],
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-017',
    title: 'SQL Injection via string formatting',
    description: 'A SQL string is interpolated with .format() or the % operator. Use parameterized queries instead.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /['"](?:SELECT|INSERT|UPDATE|DELETE|DROP)\b[^'"]*['"]\s*(?:\.format\s*\(|%\s*[\w([])/gi,
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-018',
    title: 'SQL query built by concatenation',
    description: 'A SQL statement is assigned to a variable and built with concatenation. Use parameterized queries.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /\b\w*(?:sql|query|stmt)\w*\s*=\s*['"](?:SELECT|INSERT|UPDATE|DELETE|DROP)\b[^'"]*['"]\s*\+/gi,
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  // A10:2021 - Server-Side Request Forgery (SSRF)
  {
    id: 'OWASP-019',
    title: 'Potential SSRF (Server-Side Request Forgery)',
    description: 'An HTTP request is made to a URL derived from user input. Validate and allowlist outbound URLs.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:axios|fetch|got|superagent|needle)\s*(?:\.\s*(?:get|post|put|delete|patch|request|head))?\s*\(\s*[^)]{0,80}(?:req\.|request\.|params\.|query\.|body\.)/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-918',
    owaspId: 'A10:2021',
  },
  {
    id: 'OWASP-020',
    title: 'Potential SSRF (Server-Side Request Forgery)',
    description: 'An HTTP request is made to a URL derived from request data. Validate and allowlist outbound URLs.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:requests\.(?:get|post|put|delete|patch|head|request)|urlopen|urllib\.request\.urlopen)\s*\(\s*[^)]{0,80}(?:request\.(?:args|form|values|json|GET|POST)|input\()/g,
    languages: ['python'],
    cweId: 'CWE-918',
    owaspId: 'A10:2021',
  },
  // A05:2021 - XML External Entity (XXE)
  {
    id: 'OWASP-021',
    title: 'Potential XXE in XML Parsing',
    description: 'XML is parsed without disabling external entities. Use defusedxml or disable entity resolution.',
    severity: Severity.Medium,
    category: FindingCategory.OWASP,
    pattern: /(?:lxml\.etree|etree)\.(?:parse|fromstring)\s*\(|xml\.sax\.make_parser\s*\(|minidom\.parse(?:String)?\s*\(/g,
    languages: ['python'],
    cweId: 'CWE-611',
    owaspId: 'A05:2021',
  },
  {
    id: 'OWASP-022',
    title: 'Potential XXE in XML Parsing',
    description: 'XML factory created without disabling external entities. Set features to disallow DOCTYPE/external entities.',
    severity: Severity.Medium,
    category: FindingCategory.OWASP,
    pattern: /(?:DocumentBuilderFactory|SAXParserFactory|XMLInputFactory|TransformerFactory)\.newInstance\s*\(/g,
    languages: ['java'],
    cweId: 'CWE-611',
    owaspId: 'A05:2021',
  },
  {
    id: 'OWASP-023',
    title: 'Potential XXE in XML Parsing',
    description: 'XmlDocument/XmlTextReader with default settings may resolve external entities. Set XmlResolver to null.',
    severity: Severity.Medium,
    category: FindingCategory.OWASP,
    pattern: /new\s+Xml(?:Document|TextReader)\s*\(/g,
    languages: ['csharp'],
    cweId: 'CWE-611',
    owaspId: 'A05:2021',
  },
  // A05:2021 - Insecure cookies
  {
    id: 'OWASP-024',
    title: 'Insecure Cookie Configuration',
    description: 'A cookie is set with httpOnly or secure disabled, exposing it to theft. Enable both flags.',
    severity: Severity.Medium,
    category: FindingCategory.OWASP,
    pattern: /(?:httpOnly|secure)\s*[:=]\s*false\b/gi,
    cweId: 'CWE-614',
    owaspId: 'A05:2021',
  },
  // A01:2021 - Open redirect
  {
    id: 'OWASP-025',
    title: 'Potential Open Redirect',
    description: 'A redirect target is derived from user input. Validate against an allowlist of destinations.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:res|response)\.redirect\s*\(\s*[^)]{0,60}(?:req\.|request\.|params\.|query\.|body\.)/g,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-601',
    owaspId: 'A01:2021',
  },
  {
    id: 'OWASP-026',
    title: 'Potential Open Redirect',
    description: 'A redirect target is derived from request data. Validate against an allowlist of destinations.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:redirect|HttpResponseRedirect)\s*\(\s*[^)]{0,60}request\.(?:args|GET|POST|values|form)/g,
    languages: ['python'],
    cweId: 'CWE-601',
    owaspId: 'A01:2021',
  },
  // A07:2021 - Identification and Authentication Failures
  {
    id: 'OWASP-027',
    title: 'JWT Signature Algorithm "none"',
    description: 'A JWT is configured with algorithm "none", disabling signature verification. Use a strong algorithm.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:algorithm|alg)\s*[:=]\s*['"]?none['"]?/gi,
    cweId: 'CWE-347',
    owaspId: 'A07:2021',
  },
  {
    id: 'OWASP-028',
    title: 'JWT Signature Verification Disabled',
    description: 'A JWT is decoded with signature verification disabled. Always verify the signature.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /jwt\.decode\s*\([^)]{0,120}(?:verify\s*=\s*False|['"]verify_signature['"]\s*:\s*False)/gi,
    languages: ['python'],
    cweId: 'CWE-347',
    owaspId: 'A07:2021',
  },
  // A02:2021 - TLS verification disabled
  {
    id: 'OWASP-029',
    title: 'TLS Certificate Verification Disabled',
    description: 'TLS certificate verification is disabled (rejectUnauthorized: false), enabling man-in-the-middle attacks.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /rejectUnauthorized\s*:\s*false/gi,
    languages: ['javascript', 'typescript'],
    cweId: 'CWE-295',
    owaspId: 'A02:2021',
  },
  {
    id: 'OWASP-030',
    title: 'TLS Certificate Verification Disabled',
    description: 'TLS verification is disabled (InsecureSkipVerify: true), enabling man-in-the-middle attacks.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /InsecureSkipVerify\s*:\s*true/g,
    languages: ['go'],
    cweId: 'CWE-295',
    owaspId: 'A02:2021',
  },
  {
    id: 'OWASP-031',
    title: 'TLS Certificate Verification Disabled',
    description: 'cURL peer verification is disabled (CURLOPT_SSL_VERIFYPEER false/0), enabling man-in-the-middle attacks.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /CURLOPT_SSL_VERIFYPEER\s*,\s*(?:false|0)\b/gi,
    languages: ['php'],
    cweId: 'CWE-295',
    owaspId: 'A02:2021',
  },
  // A09:2021 - Security Logging Failures (logging sensitive data)
  {
    id: 'OWASP-032',
    title: 'Sensitive Data in Logs',
    description: 'A secret-like value is written to logs. Avoid logging passwords, tokens or keys.',
    severity: Severity.Medium,
    category: FindingCategory.OWASP,
    // Fire only when a secret-named *variable* is interpolated, concatenated or
    // passed as a bare argument to the log call — i.e. a marker ({ ( , + % or
    // ${) is immediately followed by an (optionally member-accessed) secret
    // identifier matched as a whole word. This ignores the keyword appearing as
    // descriptive label text ("Password is empty"), as part of a longer name
    // (password_placeholder, itshop_password) or inside a masked expression
    // ('*' * len(config.itshop_password)), which are all false positives.
    pattern: /(?:console\.(?:log|info|debug|warn|error)|(?:logger|logging)\.(?:info|debug|warning|warn|error)|\bprint|\bprintln|System\.out\.print(?:ln)?|fmt\.Print(?:ln|f)?)\s*\(\s*(?:[^)]{0,120}?(?:[{(,+%]|\$\{)\s*)?(?:[A-Za-z_]\w*\.)*(?:password|passwd|pwd|secret|api[_-]?key|access[_-]?token|client[_-]?secret|auth[_-]?token|private[_-]?key|credit[_-]?card)\b/gi,
    cweId: 'CWE-532',
    owaspId: 'A09:2021',
  },
  // A08:2021 - Insecure Deserialization (non-Python)
  {
    id: 'OWASP-033',
    title: 'Insecure Deserialization (Java)',
    description: 'ObjectInputStream.readObject() can execute arbitrary code on untrusted input. Avoid native serialization.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /new\s+ObjectInputStream\b|\.readObject\s*\(\s*\)/g,
    languages: ['java'],
    cweId: 'CWE-502',
    owaspId: 'A08:2021',
  },
  {
    id: 'OWASP-034',
    title: 'Insecure Deserialization (PHP)',
    description: 'unserialize() on untrusted input can lead to object injection. Use json_decode for data.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /\bunserialize\s*\(/g,
    languages: ['php'],
    cweId: 'CWE-502',
    owaspId: 'A08:2021',
  },
  {
    id: 'OWASP-035',
    title: 'Insecure Deserialization (Ruby)',
    description: 'Marshal.load / YAML.load on untrusted input can execute arbitrary code. Use YAML.safe_load / JSON.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /(?:Marshal\.load|YAML\.load|Oj\.load)\s*\(/g,
    languages: ['ruby'],
    cweId: 'CWE-502',
    owaspId: 'A08:2021',
  },
  {
    id: 'OWASP-036',
    title: 'Insecure Deserialization (.NET)',
    description: 'BinaryFormatter and similar serializers are unsafe on untrusted input. Use a safe serializer.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /\b(?:BinaryFormatter|NetDataContractSerializer|LosFormatter|SoapFormatter)\b/g,
    languages: ['csharp'],
    cweId: 'CWE-502',
    owaspId: 'A08:2021',
  },
  // A03:2021 - Command injection (additional languages)
  {
    id: 'OWASP-037',
    title: 'Potential Command Injection (PHP)',
    description: 'A shell command includes a PHP variable. Use escapeshellarg() or avoid shell execution.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:system|exec|shell_exec|passthru|popen|proc_open)\s*\(\s*[^)]{0,80}\$/g,
    languages: ['php'],
    cweId: 'CWE-78',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-038',
    title: 'Potential Command Injection (Ruby)',
    description: 'A shell command interpolates a variable. Use a parameterized form of system/exec.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:system|exec|spawn)\s*\(?\s*["'][^"'\n]{0,80}#\{|`[^`\n]{0,80}#\{/g,
    languages: ['ruby'],
    cweId: 'CWE-78',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-039',
    title: 'Potential Command Injection (Go)',
    description: 'exec.Command builds an argument via concatenation. Pass arguments separately, never via a shell string.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /exec\.Command\s*\(\s*[^)]{0,80}\+/g,
    languages: ['go'],
    cweId: 'CWE-78',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-040',
    title: 'Potential Command Injection (.NET)',
    description: 'Process.Start builds a command via concatenation. Validate input and avoid shell interpretation.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /Process\.Start\s*\(\s*[^)]{0,80}\+/g,
    languages: ['csharp'],
    cweId: 'CWE-78',
    owaspId: 'A03:2021',
  },
  // A03:2021 - SQL injection (additional languages)
  {
    id: 'OWASP-041',
    title: 'Potential SQL Injection (.NET)',
    description: 'A SQL command is built with concatenation or string interpolation. Use parameterized queries.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    pattern: /(?:SqlCommand|OleDbCommand|MySqlCommand|ExecuteReader|ExecuteNonQuery|ExecuteScalar)\s*\(\s*(?:[@$]?"[^"]{0,120}"\s*\+|\$"[^"]{0,120}\{)/g,
    languages: ['csharp'],
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-042',
    title: 'Potential SQL Injection (PHP)',
    description: 'A SQL query includes a PHP variable directly. Use prepared statements with bound parameters.',
    severity: Severity.Critical,
    category: FindingCategory.OWASP,
    // Require the variable to appear inside the SQL string (double-quote
    // interpolation) or a concatenation, so the mysqli connection arg ($conn)
    // does not trigger a false positive.
    pattern: /(?:mysqli_query|mysql_query|pg_query|->query|->exec)\s*\([^;)]{0,160}(?:"[^"]{0,140}\$|\.\s*\$)/g,
    languages: ['php'],
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
  {
    id: 'OWASP-043',
    title: 'Potential SQL Injection (Go)',
    description: 'A SQL query is built with fmt.Sprintf or concatenation. Use placeholders and pass args separately.',
    severity: Severity.High,
    category: FindingCategory.OWASP,
    pattern: /\.(?:Query|QueryRow|Exec)\s*\(\s*(?:fmt\.Sprintf|[^),]{0,120}\+)/g,
    languages: ['go'],
    cweId: 'CWE-89',
    owaspId: 'A03:2021',
  },
];
